name: glow2021v1
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+7

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  vector_math: any
  #rxdart: ^0.27.2
  rxdart: ^0.23.1
  flutter_bloc: ^7.2.0
  poly_geofence_service: ^1.4.2
  #flutter_compass: ^0.7.0
  flutter_compass: ^0.3.4
  maps_toolkit: ^2.0.0
  lamp:
    git:
      url: https://github.com/a805429509/flutter_lamp.git
  permission_handler: ^8.2.5

  flutter:
    sdk: flutter
  avatar_glow: 2.0.1

  cupertino_icons: ^1.0.2
  location: any

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:


  uses-material-design: true
  assets:
    - images/
  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Regular.ttf


