name: glow2021v1
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+5

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:

  #Poly Geofence
  poly_geofence_service: ^1.4.2
  #Mobile Compass flutter_compass: ^0.7.0
  flutter_compass: ^0.3.4
  #Distance Calculation Tools
  maps_toolkit: ^2.0.0
  vector_math: any
  #Flash Light
  lamp:
    git:
      url: https://github.com/a805429509/flutter_lamp.git
  permission_handler: ^8.2.5
  #Ripple Effect
  avatar_glow: 2.0.1
  #Icon
  cupertino_icons: ^1.0.2
  #Location
  location: any
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:


  uses-material-design: true
  assets:
    - images/
  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Regular.ttf


